version: '3'

services:
  web:
    build: .
    command: gunicorn catalyst_count.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=catalyst_count_db
      - DB_USER=catalyst_user
      - DB_PASSWORD=siddharth
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=catalyst_count_db
      - POSTGRES_USER=catalyst_user
      - POSTGRES_PASSWORD=siddharth

volumes:
  postgres_data:

