# Generated by Django 4.2.15 on 2024-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.URLField(blank=True, max_length=255, null=True)),
                ('year_founded', models.PositiveIntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('size_range', models.CharField(blank=True, max_length=255, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('current_employee_estimate', models.BigIntegerField(blank=True, null=True)),
                ('total_employee_estimate', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
