# Generated by Django 4.2.15 on 2024-08-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
